[package]
name = "waifu2x"
version = "0.1.0"
authors = ["DarkSky"]
edition = "2018"
links = "waifu2x"
description = "A waifu2x-ncnn-vulkan Rust binding"
license = "AGPL-3.0-or-later"
homepage = "https://github.com/darkskygit/waifu2x.rs"
repository = "https://github.com/darkskygit/waifu2x.rs"
keywords = ["binding", "waifu2x", "ncnn", "vulkan"]
include = ["src/**/*", "waifu2x/**/*", "build.rs", "LICENSE", "README.md"]
readme = "README.md"

[features]
default = []
noise = []
noise_outside_model = []
upconv7 = []
upconv7_outside_model = []
model_bundled = []

[dependencies]
libc = "0.2.98"
ncnn-sys = { git = "https://github.com/danyspin97/waifu2x.rs", branch = "ncnn-sys" }

[dependencies.image]
version = "0.23.14"
default-features = false

[build-dependencies]
cmake = "0.1.45"
path-absolutize = "3.0.10"
