[package]
name = "ncnn-sys"
version = "0.1.1"
authors = ["DarkSky"]
edition = "2018"
links = "ncnn"
license-file = "ncnn/LICENSE.txt"
description = "just a ncnn rust unsafe binding"
homepage = "https://github.com/darkskygit/waifu2x.rs"
repository = "https://github.com/darkskygit/waifu2x.rs"
keywords = ["binding", "ncnn"]
exclude = ["ncnn/tools/*", "vulkan/**/*.pdb", "**/.git"]
readme = "README.md"

[features]
default = ["bundled"]
bundled = []

[build-dependencies]
cmake = "0.1.42"
path-absolutize = "1.1.7"
fs_extra = "1.1.0"